name: release
on: [ workflow_dispatch ]
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_LABELS: release
        run: |
          gem install -N git-pr-release -v "1.2.0"
          git-pr-release --no-fetch
