name: release
on: [ workflow_dispatch ]
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_LABELS: release
